'use strict';
console.log('hi there');
const musicContainer = document.querySelector('.music-container ');
const musicContainer = document.querySelector('.music-container ');
const musicContainer = document.querySelector('.music-container ');
const musicContainer = document.querySelector('.music-container ');
const musicContainer = document.querySelector('.music-container ');
const musicContainer = document.querySelector('.music-container ');
const musicContainer = document.querySelector('.music-container ');
const musicContainer = document.querySelector('.music-container ');
const musicContainer = document.querySelector('.music-container ');
const musicContainer = document.querySelector('.music-container ');
const musicContainer = document.querySelector('.music-container ');
